/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TipsOfTheDayUsers service. Represents a row in the &quot;rivetlogic_tod_TipsOfTheDayUsers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.model.impl.TipsOfTheDayUsersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.model.impl.TipsOfTheDayUsersImpl}.
 * </p>
 *
 * @author juancarrillo
 * @see TipsOfTheDayUsers
 * @see com.rivetlogic.model.impl.TipsOfTheDayUsersImpl
 * @see com.rivetlogic.model.impl.TipsOfTheDayUsersModelImpl
 * @generated
 */
public interface TipsOfTheDayUsersModel extends BaseModel<TipsOfTheDayUsers> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Tips of the Day Users model instance should use the {@link TipsOfTheDayUsers} interface instead.
	 */

	/**
	 * Returns the primary key of this Tips of the Day Users.
	 *
	 * @return the primary key of this Tips of the Day Users
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Tips of the Day Users.
	 *
	 * @param primaryKey the primary key of this Tips of the Day Users
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tip user ID of this Tips of the Day Users.
	 *
	 * @return the tip user ID of this Tips of the Day Users
	 */
	public long getTipUserId();

	/**
	 * Sets the tip user ID of this Tips of the Day Users.
	 *
	 * @param tipUserId the tip user ID of this Tips of the Day Users
	 */
	public void setTipUserId(long tipUserId);

	/**
	 * Returns the tip user uuid of this Tips of the Day Users.
	 *
	 * @return the tip user uuid of this Tips of the Day Users
	 * @throws SystemException if a system exception occurred
	 */
	public String getTipUserUuid() throws SystemException;

	/**
	 * Sets the tip user uuid of this Tips of the Day Users.
	 *
	 * @param tipUserUuid the tip user uuid of this Tips of the Day Users
	 */
	public void setTipUserUuid(String tipUserUuid);

	/**
	 * Returns the company ID of this Tips of the Day Users.
	 *
	 * @return the company ID of this Tips of the Day Users
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this Tips of the Day Users.
	 *
	 * @param companyId the company ID of this Tips of the Day Users
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this Tips of the Day Users.
	 *
	 * @return the group ID of this Tips of the Day Users
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this Tips of the Day Users.
	 *
	 * @param groupId the group ID of this Tips of the Day Users
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this Tips of the Day Users.
	 *
	 * @return the user ID of this Tips of the Day Users
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this Tips of the Day Users.
	 *
	 * @param userId the user ID of this Tips of the Day Users
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Tips of the Day Users.
	 *
	 * @return the user uuid of this Tips of the Day Users
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Tips of the Day Users.
	 *
	 * @param userUuid the user uuid of this Tips of the Day Users
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the status of this Tips of the Day Users.
	 *
	 * @return the status of this Tips of the Day Users
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this Tips of the Day Users.
	 *
	 * @param status the status of this Tips of the Day Users
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TipsOfTheDayUsers tipsOfTheDayUsers);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TipsOfTheDayUsers> toCacheModel();

	@Override
	public TipsOfTheDayUsers toEscapedModel();

	@Override
	public TipsOfTheDayUsers toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}