/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TipsOfTheDayCategories service. Represents a row in the &quot;rivetlogic_tod_TipsOfTheDayCategories&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.model.impl.TipsOfTheDayCategoriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.model.impl.TipsOfTheDayCategoriesImpl}.
 * </p>
 *
 * @author juancarrillo
 * @see TipsOfTheDayCategories
 * @see com.rivetlogic.model.impl.TipsOfTheDayCategoriesImpl
 * @see com.rivetlogic.model.impl.TipsOfTheDayCategoriesModelImpl
 * @generated
 */
public interface TipsOfTheDayCategoriesModel extends BaseModel<TipsOfTheDayCategories> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Tips of the Day Categories model instance should use the {@link TipsOfTheDayCategories} interface instead.
	 */

	/**
	 * Returns the primary key of this Tips of the Day Categories.
	 *
	 * @return the primary key of this Tips of the Day Categories
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Tips of the Day Categories.
	 *
	 * @param primaryKey the primary key of this Tips of the Day Categories
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the group ID of this Tips of the Day Categories.
	 *
	 * @return the group ID of this Tips of the Day Categories
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this Tips of the Day Categories.
	 *
	 * @param groupId the group ID of this Tips of the Day Categories
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the categories of this Tips of the Day Categories.
	 *
	 * @return the categories of this Tips of the Day Categories
	 */
	@AutoEscape
	public String getCategories();

	/**
	 * Sets the categories of this Tips of the Day Categories.
	 *
	 * @param categories the categories of this Tips of the Day Categories
	 */
	public void setCategories(String categories);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TipsOfTheDayCategories tipsOfTheDayCategories);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TipsOfTheDayCategories> toCacheModel();

	@Override
	public TipsOfTheDayCategories toEscapedModel();

	@Override
	public TipsOfTheDayCategories toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}