/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.services.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.rivetlogic.services.model.TipsOfTheDayVisited;
import com.rivetlogic.services.service.TipsOfTheDayVisitedLocalServiceUtil;

/**
 * The extended model base implementation for the TipsOfTheDayVisited service. Represents a row in the &quot;rivetlogic_tipday_TipsOfTheDayVisited&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TipsOfTheDayVisitedImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipsOfTheDayVisitedImpl
 * @see TipsOfTheDayVisited
 * @generated
 */
@ProviderType
public abstract class TipsOfTheDayVisitedBaseImpl
	extends TipsOfTheDayVisitedModelImpl implements TipsOfTheDayVisited {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Tips of the Day Visited model instance should use the {@link TipsOfTheDayVisited} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TipsOfTheDayVisitedLocalServiceUtil.addTipsOfTheDayVisited(this);
		}
		else {
			TipsOfTheDayVisitedLocalServiceUtil.updateTipsOfTheDayVisited(this);
		}
	}
}