/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.services.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.rivetlogic.services.model.TipsOfTheDayCategories;
import com.rivetlogic.services.service.TipsOfTheDayCategoriesLocalServiceUtil;

/**
 * The extended model base implementation for the TipsOfTheDayCategories service. Represents a row in the &quot;rivetlogic_tipday_TipsOfTheDayCategories&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TipsOfTheDayCategoriesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipsOfTheDayCategoriesImpl
 * @see TipsOfTheDayCategories
 * @generated
 */
@ProviderType
public abstract class TipsOfTheDayCategoriesBaseImpl
	extends TipsOfTheDayCategoriesModelImpl implements TipsOfTheDayCategories {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Tips of the Day Categories model instance should use the {@link TipsOfTheDayCategories} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TipsOfTheDayCategoriesLocalServiceUtil.addTipsOfTheDayCategories(this);
		}
		else {
			TipsOfTheDayCategoriesLocalServiceUtil.updateTipsOfTheDayCategories(this);
		}
	}
}