/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import com.rivetlogic.services.service.persistence.TipsOfTheDayVisitedPK;

import java.io.Serializable;

/**
 * The base model interface for the TipsOfTheDayVisited service. Represents a row in the &quot;rivetlogic_tipday_TipsOfTheDayVisited&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.services.model.impl.TipsOfTheDayVisitedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.services.model.impl.TipsOfTheDayVisitedImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipsOfTheDayVisited
 * @see com.rivetlogic.services.model.impl.TipsOfTheDayVisitedImpl
 * @see com.rivetlogic.services.model.impl.TipsOfTheDayVisitedModelImpl
 * @generated
 */
@ProviderType
public interface TipsOfTheDayVisitedModel extends BaseModel<TipsOfTheDayVisited>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Tips of the Day Visited model instance should use the {@link TipsOfTheDayVisited} interface instead.
	 */

	/**
	 * Returns the primary key of this Tips of the Day Visited.
	 *
	 * @return the primary key of this Tips of the Day Visited
	 */
	public TipsOfTheDayVisitedPK getPrimaryKey();

	/**
	 * Sets the primary key of this Tips of the Day Visited.
	 *
	 * @param primaryKey the primary key of this Tips of the Day Visited
	 */
	public void setPrimaryKey(TipsOfTheDayVisitedPK primaryKey);

	/**
	 * Returns the user ID of this Tips of the Day Visited.
	 *
	 * @return the user ID of this Tips of the Day Visited
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this Tips of the Day Visited.
	 *
	 * @param userId the user ID of this Tips of the Day Visited
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Tips of the Day Visited.
	 *
	 * @return the user uuid of this Tips of the Day Visited
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this Tips of the Day Visited.
	 *
	 * @param userUuid the user uuid of this Tips of the Day Visited
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this Tips of the Day Visited.
	 *
	 * @return the company ID of this Tips of the Day Visited
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this Tips of the Day Visited.
	 *
	 * @param companyId the company ID of this Tips of the Day Visited
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this Tips of the Day Visited.
	 *
	 * @return the group ID of this Tips of the Day Visited
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this Tips of the Day Visited.
	 *
	 * @param groupId the group ID of this Tips of the Day Visited
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the tip ID of this Tips of the Day Visited.
	 *
	 * @return the tip ID of this Tips of the Day Visited
	 */
	@AutoEscape
	public String getTipId();

	/**
	 * Sets the tip ID of this Tips of the Day Visited.
	 *
	 * @param tipId the tip ID of this Tips of the Day Visited
	 */
	public void setTipId(String tipId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TipsOfTheDayVisited tipsOfTheDayVisited);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TipsOfTheDayVisited> toCacheModel();

	@Override
	public TipsOfTheDayVisited toEscapedModel();

	@Override
	public TipsOfTheDayVisited toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}