/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rivetlogic.model.TipsOfTheDayVisited;

import com.rivetlogic.service.TipsOfTheDayVisitedLocalServiceUtil;

/**
 * The extended model base implementation for the TipsOfTheDayVisited service. Represents a row in the &quot;rivetlogic_tod_TipsOfTheDayVisited&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TipsOfTheDayVisitedImpl}.
 * </p>
 *
 * @author juancarrillo
 * @see TipsOfTheDayVisitedImpl
 * @see com.rivetlogic.model.TipsOfTheDayVisited
 * @generated
 */
public abstract class TipsOfTheDayVisitedBaseImpl
	extends TipsOfTheDayVisitedModelImpl implements TipsOfTheDayVisited {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Tips of the Day Visited model instance should use the {@link TipsOfTheDayVisited} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TipsOfTheDayVisitedLocalServiceUtil.addTipsOfTheDayVisited(this);
		}
		else {
			TipsOfTheDayVisitedLocalServiceUtil.updateTipsOfTheDayVisited(this);
		}
	}
}